### ISSUE TITLE
TypeError: Cannot set property 'identitySource' of undefined

### ISSUE THREAD

**Issue by jpswade** [zanona/swagger2tf#1]
```
/usr/local/lib/node_modules/swagger2tf/index.js:103
    authorizer.identitySource = `${definition.in}.${definition.name}`;
                              ^

TypeError: Cannot set property 'identitySource' of undefined
    at EventEmitter.runParser (/usr/local/lib/node_modules/swagger2tf/index.js:103:31)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by lintaonz** [comment]
I got the same issue because swagger2tf doesn't support [aws_api_gateway_api_key](https://www.terraform.io/docs/providers/aws/r/api_gateway_api_key.html). 

> securityDefinitions:
>   api_key:
>     type: "apiKey"
>     name: "x-api-key"
>     in: "header"

And this is not a easy fix because you need to define usage plan and stage with the api-key.
